/*
 * This file is generated by jOOQ.
 */
package com.armin.revolut.models;


import com.armin.revolut.models.tables.Account;
import com.armin.revolut.models.tables.Records;
import com.armin.revolut.models.tables.records.AccountRecord;
import com.armin.revolut.models.tables.records.RecordsRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountRecord, Long> IDENTITY_ACCOUNT = Identities0.IDENTITY_ACCOUNT;
    public static final Identity<RecordsRecord, Long> IDENTITY_RECORDS = Identities0.IDENTITY_RECORDS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> CONSTRAINT_E = UniqueKeys0.CONSTRAINT_E;
    public static final UniqueKey<AccountRecord> CONSTRAINT_E4 = UniqueKeys0.CONSTRAINT_E4;
    public static final UniqueKey<RecordsRecord> CONSTRAINT_6 = UniqueKeys0.CONSTRAINT_6;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<RecordsRecord, AccountRecord> FK_ACCOUNT_ID = ForeignKeys0.FK_ACCOUNT_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AccountRecord, Long> IDENTITY_ACCOUNT = Internal.createIdentity(Account.ACCOUNT, Account.ACCOUNT.ID);
        public static Identity<RecordsRecord, Long> IDENTITY_RECORDS = Internal.createIdentity(Records.RECORDS, Records.RECORDS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> CONSTRAINT_E = Internal.createUniqueKey(Account.ACCOUNT, "CONSTRAINT_E", Account.ACCOUNT.ID);
        public static final UniqueKey<AccountRecord> CONSTRAINT_E4 = Internal.createUniqueKey(Account.ACCOUNT, "CONSTRAINT_E4", Account.ACCOUNT.CODE);
        public static final UniqueKey<RecordsRecord> CONSTRAINT_6 = Internal.createUniqueKey(Records.RECORDS, "CONSTRAINT_6", Records.RECORDS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<RecordsRecord, AccountRecord> FK_ACCOUNT_ID = Internal.createForeignKey(com.armin.revolut.models.Keys.CONSTRAINT_E, Records.RECORDS, "FK_ACCOUNT_ID", Records.RECORDS.ACCOUNT_ID);
    }
}
