/*
 * This file is generated by jOOQ.
 */
package com.armin.revolut.models;


import com.armin.revolut.models.tables.Account;
import com.armin.revolut.models.tables.Records;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>RECORDS</code>.
     */
    public static final Records RECORDS = Records.RECORDS;
}
